from MplWidget import MplWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 528)
        MainWindow.setMaximumSize(QtCore.QSize(978, 528))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-image: url(https://naurok-test.nyc3.cdn.digitaloceanspaces.com/248846/images/336859_1586277009.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 991, 581))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(18, 18))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.Data = QtWidgets.QWidget()
        self.Data.setObjectName("Data")
        self.textBrowser = QtWidgets.QTextBrowser(self.Data)
        self.textBrowser.setGeometry(QtCore.QRect(50, 10, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"background-color: #FFFFFC;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.lineal = QtWidgets.QRadioButton(self.Data)
        self.lineal.setGeometry(QtCore.QRect(210, 370, 82, 17))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.lineal.setFont(font)
        self.lineal.setObjectName("lineal")
        self.regions = QtWidgets.QComboBox(self.Data)
        self.regions.setGeometry(QtCore.QRect(140, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(15)
        font.setItalic(False)
        self.regions.setFont(font)
        self.regions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.regions.setStyleSheet("QComboBox {\n"
"background-color: #FFFFFC;\n"
"color: black;\n"
"}")
        self.regions.setObjectName("regions")
        self.regions.addItem("")
        # self.regions.addItem("")
        # self.regions.addItem("")
        # self.regions.addItem("")
        # self.regions.addItem("")
        # self.regions.addItem("")
        # self.regions.addItem("")
        # self.regions.addItem("")
        # self.regions.addItem("")
        self.label_2 = QtWidgets.QLabel(self.Data)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.polynomial = QtWidgets.QRadioButton(self.Data)
        self.polynomial.setGeometry(QtCore.QRect(110, 370, 91, 17))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.polynomial.setFont(font)
        self.polynomial.setObjectName("polynomial")
        self.table = QtWidgets.QTableWidget(self.Data)
        self.table.setGeometry(QtCore.QRect(330, 0, 641, 461))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.table.setFont(font)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.label = QtWidgets.QLabel(self.Data)
        self.label.setGeometry(QtCore.QRect(50, 110, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnBrowse = QtWidgets.QPushButton(self.Data)
        self.btnBrowse.setGeometry(QtCore.QRect(100, 400, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(18)
        self.btnBrowse.setFont(font)
        self.btnBrowse.setStyleSheet("QPushButton {\n"
"background-color: #330036;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #58085C;\n"
"}")
        self.btnBrowse.setObjectName("btnBrowse")
        self.radioButton_3 = QtWidgets.QRadioButton(self.Data)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 370, 82, 17))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_3 = QtWidgets.QLabel(self.Data)
        self.label_3.setGeometry(QtCore.QRect(80, 330, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.listmonth = QtWidgets.QComboBox(self.Data)
        self.listmonth.setGeometry(QtCore.QRect(140, 150, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(15)
        font.setItalic(False)
        self.listmonth.setFont(font)
        self.listmonth.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listmonth.setStyleSheet("QComboBox {\n"
"background-color: #FFFFFC;\n"
"color: black;\n"
"}")
        self.listmonth.setObjectName("listmonth")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.listmonth.addItem("")
        self.label_5 = QtWidgets.QLabel(self.Data)
        self.label_5.setGeometry(QtCore.QRect(50, 190, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Data)
        self.label_6.setGeometry(QtCore.QRect(50, 230, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Data)
        self.label_7.setGeometry(QtCore.QRect(50, 270, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.fromdata = QtWidgets.QDateEdit(self.Data)
        self.fromdata.setGeometry(QtCore.QRect(100, 240, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        self.fromdata.setFont(font)
        self.fromdata.setDateTime(QtCore.QDateTime(QtCore.QDate(2012, 11, 14), QtCore.QTime(0, 0, 0)))
        self.fromdata.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2012, 12, 31), QtCore.QTime(23, 59, 59)))
        self.fromdata.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2012, 1, 1), QtCore.QTime(0, 0, 0)))
        self.fromdata.setObjectName("fromdata")
        self.todata = QtWidgets.QDateEdit(self.Data)
        self.todata.setGeometry(QtCore.QRect(100, 280, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        self.todata.setFont(font)
        self.todata.setDateTime(QtCore.QDateTime(QtCore.QDate(2012, 11, 14), QtCore.QTime(0, 0, 0)))
        self.todata.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2012, 12, 31), QtCore.QTime(23, 59, 59)))
        self.todata.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2012, 1, 1), QtCore.QTime(0, 0, 0)))
        self.todata.setObjectName("todata")
        self.spinBox = QtWidgets.QSpinBox(self.Data)
        self.spinBox.setGeometry(QtCore.QRect(120, 200, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(31)
        self.spinBox.setObjectName("spinBox")
        self.tabWidget.addTab(self.Data, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget = MplWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(30, 10, 631, 391))
        self.widget.setObjectName("widget")
        self.listmonth_2 = QtWidgets.QComboBox(self.tab_2)
        self.listmonth_2.setGeometry(QtCore.QRect(680, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(15)
        font.setItalic(False)
        self.listmonth_2.setFont(font)
        self.listmonth_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listmonth_2.setStyleSheet("QComboBox {\n"
"background-color: #FFFFFC;\n"
"color: black;\n"
"}")
        self.listmonth_2.setObjectName("listmonth_2")
        self.listmonth_2.addItem("")
        self.listmonth_2.addItem("")
        self.listmonth_2.addItem("")
        self.do_1 = QtWidgets.QPushButton(self.tab_2)
        self.do_1.setGeometry(QtCore.QRect(350, 410, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(18)
        self.do_1.setFont(font)
        self.do_1.setStyleSheet("QPushButton {\n"
"background-color: #330036;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #58085C;\n"
"}")
        self.do_1.setObjectName("do_1")
        self.table_2 = QtWidgets.QTableWidget(self.tab_2)
        self.table_2.setGeometry(QtCore.QRect(680, 80, 291, 291))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.table_2.setFont(font)
        self.table_2.setObjectName("table_2")
        self.table_2.setColumnCount(0)
        self.table_2.setRowCount(0)
        self.listmonth_3 = QtWidgets.QComboBox(self.tab_2)
        self.listmonth_3.setGeometry(QtCore.QRect(30, 410, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(15)
        font.setItalic(False)
        self.listmonth_3.setFont(font)
        self.listmonth_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listmonth_3.setStyleSheet("QComboBox {\n"
"background-color: #FFFFFC;\n"
"color: black;\n"
"}")
        self.listmonth_3.setObjectName("listmonth_3")
        self.listmonth_3.addItem("")
        self.listmonth_3.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget_2 = MplWidget(self.tab)
        self.widget_2.setGeometry(QtCore.QRect(20, 10, 631, 391))
        self.widget_2.setObjectName("widget_2")
        self.do_2 = QtWidgets.QPushButton(self.tab)
        self.do_2.setGeometry(QtCore.QRect(740, 50, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(18)
        self.do_2.setFont(font)
        self.do_2.setStyleSheet("QPushButton {\n"
"background-color: #330036;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #58085C;\n"
"}")
        self.do_2.setObjectName("do_2")
        self.listmonth_4 = QtWidgets.QComboBox(self.tab)
        self.listmonth_4.setGeometry(QtCore.QRect(680, 110, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(15)
        font.setItalic(False)
        self.listmonth_4.setFont(font)
        self.listmonth_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listmonth_4.setStyleSheet("QComboBox {\n"
"background-color: #FFFFFC;\n"
"color: black;\n"
"}")
        self.listmonth_4.setObjectName("listmonth_4")
        self.listmonth_4.addItem("")
        self.listmonth_4.addItem("")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bahnschrift Light SemiCondensed\'; font-size:14pt;\">Оберіть місяць, щоб отримати інформацію про погоду в регіоні</span></p></body></html>"))
        self.lineal.setText(_translate("MainWindow", "Lineal"))
        self.regions.setItemText(0, _translate("MainWindow", "Київ"))
        # self.regions.setItemText(1, _translate("MainWindow", "Одеса"))
        # self.regions.setItemText(2, _translate("MainWindow", "Івано-Франківськ"))
        # self.regions.setItemText(3, _translate("MainWindow", "Дніпро"))
        # self.regions.setItemText(4, _translate("MainWindow", "Донецьк"))
        # self.regions.setItemText(5, _translate("MainWindow", "Симферополь"))
        # self.regions.setItemText(6, _translate("MainWindow", "Луганськ"))
        # self.regions.setItemText(7, _translate("MainWindow", "Львів"))
        # self.regions.setItemText(8, _translate("MainWindow", "Черкаси"))
        self.label_2.setText(_translate("MainWindow", "Місяць:"))
        self.polynomial.setText(_translate("MainWindow", "Polynomial"))
        self.label.setText(_translate("MainWindow", "Регіон:"))
        self.btnBrowse.setText(_translate("MainWindow", "Обрати"))
        self.radioButton_3.setText(_translate("MainWindow", "Nearest"))
        self.label_3.setText(_translate("MainWindow", "Метод інтерполяції:"))
        self.listmonth.setItemText(0, _translate("MainWindow", "Січень"))
        self.listmonth.setItemText(1, _translate("MainWindow", "Лютий"))
        self.listmonth.setItemText(2, _translate("MainWindow", "Березень"))
        self.listmonth.setItemText(3, _translate("MainWindow", "Квітень"))
        self.listmonth.setItemText(4, _translate("MainWindow", "Травень"))
        self.listmonth.setItemText(5, _translate("MainWindow", "Червень"))
        self.listmonth.setItemText(6, _translate("MainWindow", "Липень"))
        self.listmonth.setItemText(7, _translate("MainWindow", "Серпень"))
        self.listmonth.setItemText(8, _translate("MainWindow", "Вересень"))
        self.listmonth.setItemText(9, _translate("MainWindow", "Жовтень"))
        self.listmonth.setItemText(10, _translate("MainWindow", "Листопад"))
        self.listmonth.setItemText(11, _translate("MainWindow", "Грудень"))
        self.label_5.setText(_translate("MainWindow", "День:"))
        self.label_6.setText(_translate("MainWindow", "Від:"))
        self.label_7.setText(_translate("MainWindow", "До:"))
        self.fromdata.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.todata.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Data), _translate("MainWindow", "Data"))
        self.listmonth_2.setItemText(0, _translate("MainWindow", "Статистика від-до"))
        self.listmonth_2.setItemText(1, _translate("MainWindow", "Статистика за місяць"))
        self.listmonth_2.setItemText(2, _translate("MainWindow", "Статистика за день"))
        self.do_1.setText(_translate("MainWindow", "Побудувати"))
        self.listmonth_3.setItemText(0, _translate("MainWindow", "Температурні умови регіону"))
        self.listmonth_3.setItemText(1, _translate("MainWindow", "Тривалість температурних режимів"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Temperature"))
        self.do_2.setText(_translate("MainWindow", "Побудувати"))
        self.listmonth_4.setItemText(0, _translate("MainWindow", "Тривалість режимів вітрової активності"))
        self.listmonth_4.setItemText(1, _translate("MainWindow", "Троянда вітрів"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Wind"))

